# 05 no_documensts.R
# ------------------------------------------------------------------------------


setwd("D:/Dropbox (Personal)/liaad-drop/d = data/[1] Datasets/20ng")


# extract data -----------------------------------------------------------------
alt_atheism              <- Corpus(DirSource("./alt.atheism"), readerControl=list(reader=readMail, language="en")) 
comp_graphics            <- Corpus(DirSource("./comp.graphics"), readerControl=list(reader=readMail, language="en")) 
comp_os_mswindows_misc   <- Corpus(DirSource("./comp.os.ms-windows.misc"), readerControl=list(reader=readMail, language="en"))
comp_sys_ibm_pc_hardware <- Corpus(DirSource("./comp.sys.ibm.pc.hardware"), readerControl=list(reader=readMail, language="en"))
comp_sys_mac_hardware    <- Corpus(DirSource("./comp.sys.mac.hardware"), readerControl=list(reader=readMail, language="en"))
misc_forsale             <- Corpus(DirSource("./misc.forsale"), readerControl=list(reader=readMail, language="en"))
comp_windows_x           <- Corpus(DirSource("./comp.windows.x"), readerControl=list(reader=readMail, language="en"))
rec_autos                <- Corpus(DirSource("./rec.autos"), readerControl=list(reader=readMail, language="en"))
rec_motorcycles          <- Corpus(DirSource("./rec.motorcycles"), readerControl=list(reader=readMail, language="en"))
rec_sport_baseball       <- Corpus(DirSource("./rec.sport.baseball"), readerControl=list(reader=readMail, language="en"))
rec_sport_hockey         <- Corpus(DirSource("./rec.sport.hockey"), readerControl=list(reader=readMail, language="en"))
sci_crypt                <- Corpus(DirSource("./sci.crypt"), readerControl=list(reader=readMail, language="en"))
sci_electronics          <- Corpus(DirSource("./sci.electronics"), readerControl=list(reader=readMail, language="en"))
sci_med                  <- Corpus(DirSource("./sci.med"), readerControl=list(reader=readMail, language="en"))
sci_space                <- Corpus(DirSource("./sci.space"), readerControl=list(reader=readMail, language="en"))
soc_religion_christian   <- Corpus(DirSource("./soc.religion.christian"), readerControl=list(reader=readMail, language="en"))
talk_politics_guns       <- Corpus(DirSource("./talk.politics.guns"), readerControl=list(reader=readMail, language="en"))
talk_politics_mideast    <- Corpus(DirSource("./talk.politics.mideast"), readerControl=list(reader=readMail, language="en"))
talk_politics_misc       <- Corpus(DirSource("./talk.politics.misc"), readerControl=list(reader=readMail, language="en"))
talk_religion_misc  	 <- Corpus(DirSource("./talk.religion.misc"), readerControl=list(reader=readMail, language="en"))


setwd("D:/Dropbox (Personal)/liaad-drop/d = data/[1] Datasets/ohsumed-all")
# labels -----------------------------------------------------------------------
animal					 <- VCorpus(DirSource("./animal")				   , readerControl = list(reader = readPlain, language = "en"))
bacterial_infec_mycoses  <- VCorpus(DirSource("./bacterial_infec_mycoses") , readerControl = list(reader = readPlain, language = "en"))
cardiovascular           <- VCorpus(DirSource("./cardiovascular") 		   , readerControl = list(reader = readPlain, language = "en"))
digestive_syst           <- VCorpus(DirSource("./digestive_syst")		   , readerControl = list(reader = readPlain, language = "en"))
disorders_environmental  <- VCorpus(DirSource("./disorders_environmental") , readerControl = list(reader = readPlain, language = "en"))
endocrine                <- VCorpus(DirSource("./endocrine")			   , readerControl = list(reader = readPlain, language = "en"))
eye                      <- VCorpus(DirSource("./eye")					   , readerControl = list(reader = readPlain, language = "en"))
female_genital_pregnancy <- VCorpus(DirSource("./female_genital_pregnancy"), readerControl = list(reader = readPlain, language = "en"))
hemic_and_lymphatic      <- VCorpus(DirSource("./hemic_and_lymphatic")     , readerControl = list(reader = readPlain, language = "en"))
immunologic              <- VCorpus(DirSource("./immunologic")			   , readerControl = list(reader = readPlain, language = "en"))
musculoskeletal          <- VCorpus(DirSource("./musculoskeletal")         , readerControl = list(reader = readPlain, language = "en"))
neonatal_abnormalities   <- VCorpus(DirSource("./neonatal_abnormalities")  , readerControl = list(reader = readPlain, language = "en"))
neoplasms                <- VCorpus(DirSource("./neoplasms")     		   , readerControl = list(reader = readPlain, language = "en"))
nervous_syst             <- VCorpus(DirSource("./nervous_syst")  		   , readerControl = list(reader = readPlain, language = "en"))
nutritional_metabolic    <- VCorpus(DirSource("./nutritional_metabolic")   , readerControl = list(reader = readPlain, language = "en"))
otorhinolaryngologic     <- VCorpus(DirSource("./otorhinolaryngologic")	   , readerControl = list(reader = readPlain, language = "en"))
parasitic                <- VCorpus(DirSource("./parasitic")			   , readerControl = list(reader = readPlain, language = "en"))
pathological_cond_signs  <- VCorpus(DirSource("./pathological_cond_signs") , readerControl = list(reader = readPlain, language = "en"))
respiratory_tract        <- VCorpus(DirSource("./respiratory_tract")	   , readerControl = list(reader = readPlain, language = "en"))
skin_connective_tissue   <- VCorpus(DirSource("./skin_connective_tissue")  , readerControl = list(reader = readPlain, language = "en"))
stomatognathic           <- VCorpus(DirSource("./stomatognathic")		   , readerControl = list(reader = readPlain, language = "en"))
urologic_male_genital    <- VCorpus(DirSource("./urologic_male_genital")   , readerControl = list(reader = readPlain, language = "en"))
virus                    <- VCorpus(DirSource("./virus")				   , readerControl = list(reader = readPlain, language = "en"))